version: '3.8'

services:
  discord-bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Monte le code source pour hot-reload
      - ./:/app
      # Monte les dossiers de stockage persistants
      - ./screenshots:/app/screenshots
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Paris
    container_name: rtf-discord-bot-dev
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

